turn_on_with_source:
  description: "Turn on the Triad AMS zone and set the input source to that of another media player entity."
  target:
    entity:
      domain: media_player
      integration: triad_ams
  fields:
    input_entity_id:
      required: true
      example: media_player.apple_tv
      selector:
        entity:
          domain: media_player
          filter:
            supported_features:
              - media_player.MediaPlayerEntityFeature.PLAY
              - media_player.MediaPlayerEntityFeature.PLAY_MEDIA
get_joinable_group_members:
  description: "Get all speaker entities that can join this input for grouping."
  target:
    entity:
      domain: media_player
      integration: triad_ams
      device_class: receiver
  response:
    mandatory: true
    schema:
      type: object
      properties:
        joinable_members:
          type: array
          items:
            type: string
          description: "List of entity IDs that can join the current input for grouping."
