turn_on_with_source:
  description: "Turn on the Triad AMS zone and set the input source to that of another media player entity."
  target:
    entity:
      domain: media_player
      integration: triad_ams
  fields:
    input_entity_id:
      required: true
      example: media_player.apple_tv
      selector:
        entity:
          domain: media_player
          filter:
            supported_features:
              - media_player.MediaPlayerEntityFeature.PLAY
              - media_player.MediaPlayerEntityFeature.PLAY_MEDIA
get_groupable_players:
  description: "Get all speaker entities that can group with this input."
  target:
    entity:
      domain: media_player
      integration: triad_ams
      device_class: receiver
set_protocol_debug:
  description: "Enable or disable protocol-level logging for all Triad AMS entries."
  fields:
    enabled:
      required: true
      example: true
      selector:
        boolean:
